### ISSUE TITLE
Examining Different csv Files for Experimentation - Error in the Last Cell

### ISSUE THREAD

**Issue by eugenekwon20** [haoteli/Secondary-Structure-Determination-NMR#1]
Greetings,

I am a PhD student trying out the package with different examples from a lab and I have encountered the following error when running the last cell, "Running GD with parameters":

TypeError                                 Traceback (most recent call last)

[<ipython-input-6-32b48926683d>](https://localhost:8080/#) in <cell line: 230>()
    229 
    230 for epoch in tqdm(range(Epochs)): # Training model
--> 231   sim_spectrum = model(ppm,background_means = backbone_means)
    232   offset_ind = (torch.abs(model.offset) > Freedom_ppm_back)
    233   side_offset_ind = (torch.abs(model.side_offset) > Freedom_ppm_side)

2 frames

[<ipython-input-6-32b48926683d>](https://localhost:8080/#) in forward(self, ppm, background_means, costum_state)
    202 
    203 
--> 204     sim_spctra = sim_spctra/torch.sum(sim_spctra)
    205 
    206     return(sim_spctra)

TypeError: sum(): argument 'input' (position 1) must be Tensor, not int

  0%
 0/100 [00:00<?, ?it/s]

Thus far, this problem seems to occur when I am running the package with the provided examples if the package is run with different examples first. As a result, I am unsure as to why this occurs and would like to attempt submitting this in this particular section in hopes that a solution may arise. Thank you.

**Comment by haoteli** [comment]
Dear eugenekwon20,

We are excited to hear that you were able to run the algorithm for different examples from your study 😃.

- If the following is not helpful: please save and drop your notebook so that I may reproduce your exact issue.

-----------------------------------------------

Based on the description, I assume that you are using the Colab notebook implementation so I will answer under this reference.
Based on my investigation, this error traces back to the "three_in_one" function which is used to return the "sim_spectra" variable.

```python
def three_in_one(self, ppm):
    # This function sums the contribution of individual residues together

    final_spectrum = 0
    for ss_type_j in range(self.shift_table.shape[2]): # For each secondary structure
        summed_spectrum = 0
        for atom_type_i in range(self.shift_table.shape[1]): # For each atom type
            for residue_k in range(self.shift_table.shape[0]): # For each residue in the sequence
                if(~torch.isnan(self.shift_table[residue_k,atom_type_i,ss_type_j])):
                    summed_spectrum += self.g(ppm, self.shift_table[residue_k,atom_type_i,ss_type_j] + self.offset[residue_k,atom_type_i,ss_type_j] - self.re_reference, self.b2.squeeze())*self.soft_a[residue_k,ss_type_j]

        self.spectra_components[ss_type_j] = summed_spectrum
        final_spectrum += summed_spectrum
    return(final_spectrum)
``` 

As you can see, the function starts from an integer and sums it to an array. However, if the code block under the for loops is not executed, the returned object will remain an integer which will trigger the error you were seeing.


1. The first explanation is that the "self.shift_table" contains only "np.nan" values. Because in such case, the array summation will be skipped from the "if" statement in the for loop. So far, I can only imagine this happening by setting the atom types to only beta-carbons with the Glycine residue.
2.  The second explanation is the "self.shift_table" is set to an empty array. However, the model would have triggered an error during initialization if it was prepared empty.


These issues could occur if you have tried to access the model parameters (self.shit_table) and accidentally modified them.

Therefore, I would recommend restarting the notebook to correctly assign the variable and then run your sample again. 

Based on the provided traceback message, my analysis limited but I will be happy to examine more details and help out. Therefore, if you have already tried restarting and it did not work, please save and drop your notebook so that I may reproduce your exact issue.

Best Regards,
Haote

**Comment by eugenekwon20** [comment]
Greetings,

As a relative novice in using Github and Python-based packages, I apologize if I am not able to follow your words precisely. That being said, I have gone ahead and restarted the notebook as recommended and applied the correct inputs and variables to the notebook. I have previously attempted to restart the notebook to no effect, but following your instructions and saving a new notebook has done the trick and has yielded me the appropriate SSDs. Thank you very much for your openness in looking over the codes and your following suggestions despite my own limited input. I look forward to the continued success of your work.
